### ISSUE TITLE
功能增加

### ISSUE THREAD

**Issue by noob3-3** [legubiao/ros2d-quasar#1]
我觉得只是课题实现导航缺少实用价值，可以添加一些其他功能，如
可以设置机器人执行多个航点间到导航，同时可以配置每个航点到达后执行特定任务

**Comment by legubiao** [comment]
1. 多航点功能在ROS2中的navigation2似乎已经实现，不过目前rosbridge稳定版还没加入对action的支持，所以这部分会等rosbridge更新后考虑加入。
2. 之前有开发过基于任务队列和基础任务单元来实现的机制（例如，导航到点任务，机械臂抓取任务，自动充电任务等），不过这类系统一般是和公司业务绑定，此外在模拟器中我暂时也没实现除了移动以外的其他任务类型，就暂时没把这部分功能迁移过来了
